### ISSUE TITLE
I can‘t downLoad the widget

### ISSUE THREAD

**Issue by xieqiancaosissi** [near/near-vscode#10]
<img width="527" alt="image" src="https://user-images.githubusercontent.com/30308216/229020614-b566556b-50e0-42bc-b0ce-e62f05374ad1.png">

**Comment by xieqiancaosissi** [comment]
Click Login & fetch Widgets button, an error would happen in vsCode IDE。

**Comment by gagdiez** [comment]
@xieqiancaosissi please let me know if the error persists in the newest version, simply open back this issue
