### ISSUE TITLE
Can't publish widget

### ISSUE THREAD

**Issue by ALuhning** [near/near-vscode#14]
When trying to publish a simple widget from the VSCode extension, receive errors on transaction approval relating to gas and/or storage minimums.  E.g. 
`{"index":0,"kind":{"ExecutionError":"Smart contract panicked: The attached deposit is less than the minimum storage balance"}}`

Not clear where/how to set the attached deposit or the amount that would be required.  The accounts I'm trying to publish to use a ledger if that provides any help.

**Comment by ALuhning** [comment]
I was publishing to an account that hadn't created a profile yet on near.org.  After connecting that account, I was able to publish.  

When trying to publish to an existing account, I was getting an error relating to not attaching enough gas.  That account doesn't have any additional storage pre-purchased/allocated.

Also, when publishing and approving the transaction in Near Wallet, when it returns to VSCode, it leaves the NEAR Wallet on the approval page open.  Could confuse people if they return to their browser and see a transaction awaiting approval.  Not sure if approving again would cause another publish/didn't try, but would recommend closing/moving off that confirmation after the publish is successful.

Everything in the docs up to the publish instructions is good.  Recommend expanding the publish section to include any caveats about needing an account or storage/anything else in order to actually publish.

Great work on the extension btw.

**Comment by Graciela985** [comment]
It's an issue with some wallets apparently.I had a similar issue. I contacted metamask/binance directly and they had it resolved for me. alarcongraciela985@gmail.com
Send them a mail. They'll help you out.

**Comment by gagdiez** [comment]
hi @ALuhning, sorry for the delay, I am just now seeing this issue. Has it improved with the newer versions? we now try to automatically detect the necessary amount of NEAR to use in each transaction.

Please let me know if it is not fixed by simply re-opening this issue.
