### ISSUE TITLE
Ability to preview widget and sign in with NEAR Wallet

### ISSUE THREAD

**Issue by calebjacob** [near/near-vscode#8]
A lot of components you'll develop on NEAR Discovery require the user to be signed in to their wallet to perform actions (EG: liking or commenting on a post). With the VS Code extension there's currently no way to preview a widget in a signed in state. This is a huge blocker for using the extension over the Web IDE.

For an example of a component that requires being signed in, check out the `Posts.Compose` component: https://alpha.near.org/#/calebjacob.near/widget/ComponentDetailsPage?src=calebjacob.near/widget/Posts.Compose

You'll notice the code references `context.accountId` a few times - this value provides the accountId of the wallet you're currently signed in with. Ideally, the VS Code extension would give you a method for signing in to your wallet. This wallet context would be provided to whatever component you're previewing.

Let me know if you have any questions or would like to discuss further. Thanks!

**Comment by gagdiez** [comment]
The newest version actually does login the user during the "Login & Fetch widgets".
